apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    app: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: example-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        pod: example-pod
    spec:
      containers:
      - image: nginx
        name: nginx-container
        ports:
        - containerPort: 80
          name: container-port
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /usr/share/nginx/html/index.html
          name: custom-html
          subPath: index.html
        - mountPath: /usr/share/nginx/html/app.js
          name: custom-js
          subPath: app.js
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-conf
      - name: custom-html
        configMap:
          name: html
      - name: custom-js
        configMap:
          name: js
