apiVersion: v1
kind: Service
metadata:
  name: example-app-service
spec:
  type: NodePort
  selector:
    pod: example-pod
  ports:
  - name: "http-port"
    protocol: TCP
    port: 80
    targetPort: 80
